import {spawnSync} from 'node:child_process';
import {access,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const instrumentalOnly=process.argv.includes('--instrumental-only');
const browser=process.env.REMOTION_BROWSER_EXECUTABLE||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const run=(cmd,args)=>{const r=spawnSync(cmd,args,{cwd:root,stdio:'inherit',windowsHide:true});assert.equal(r.status,0,`${cmd} failed`);};
await mkdir(path.join(root,'qa'),{recursive:true});
for(const file of ['workflow.mp4','results.mp4','override.mp4','receipts.mp4','records.mp4','hero-admin.mp4'])await access(path.join(root,'public/combined',file));
if(!process.argv.includes('--mux-only'))run(process.execPath,[path.join(root,'node_modules/@remotion/cli/remotion-cli.js'),'render','src/index.ts','TunaEyeCombinedVisual','qa/combined-visual-master.mp4','--codec=h264','--crf=18','--x264-preset=fast','--concurrency=4',`--browser-executable=${browser}`]);
if(process.argv.includes('--visual-only'))process.exit(0);
for(const file of instrumentalOnly?['no_narration_mix.wav']:['final_mix.wav','no_narration_mix.wav'])await access(path.join(root,'public/combined/audio',file));
run('ffmpeg',['-hide_banner','-loglevel','error','-y','-i','qa/combined-visual-master.mp4','-vf','scale=in_color_matrix=bt601:out_color_matrix=bt709:in_range=full:out_range=limited,format=yuv420p','-c:v','libx264','-crf','18','-preset','fast','-pix_fmt','yuv420p','-color_range','tv','-colorspace','bt709','-color_primaries','bt709','-color_trc','bt709','-an','qa/combined-visual-compatible.mp4']);
const mixes=instrumentalOnly?[['no_narration_mix.wav','tunaeye-combined-product-demo-no-narration.mp4']]:[['final_mix.wav','tunaeye-combined-product-demo.mp4'],['no_narration_mix.wav','tunaeye-combined-product-demo-no-narration.mp4']];
for(const [audio,file] of mixes)run('ffmpeg',['-hide_banner','-loglevel','error','-y','-i','qa/combined-visual-compatible.mp4','-i',`public/combined/audio/${audio}`,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','320k','-ar','48000','-ac','2','-t','120','-movflags','+faststart',file]);
run('ffmpeg',['-hide_banner','-loglevel','error','-y','-i',instrumentalOnly?'tunaeye-combined-product-demo-no-narration.mp4':'tunaeye-combined-product-demo.mp4','-vf','scale=1280:720,fps=30','-c:v','libx264','-crf','24','-preset','fast','-c:a','aac','-b:a','192k','-ar','48000','-ac','2','-movflags','+faststart',instrumentalOnly?'tunaeye-combined-preview-instrumental.mp4':'tunaeye-combined-preview.mp4']);
console.log(instrumentalOnly?'Combined120-second instrumental film and preview exported; narration pending.':'Combined120-second narrated, narration-free and preview exports written.');
