import { useState } from 'react'

export type MarketingPage = 'home' | 'features' | 'about' | 'team' | 'faq' | 'terms' | 'privacy'

const pages: { id: MarketingPage; label: string }[] = [
  { id: 'home', label: 'Home' }, { id: 'features', label: 'Features' }, { id: 'about', label: 'About TunaEye' },
  { id: 'team', label: 'Team' }, { id: 'faq', label: 'FAQ' },
]

function Logo() { return <span className="site-logo"><img src="/tunaeye-logo.svg" alt="" /><strong>Tuna<span>Eye</span></strong></span> }
function Arrow() { return <span aria-hidden="true">→</span> }

export default function MarketingLanding({ page, onNavigate, onInstall, onOpen }: { page: MarketingPage; onNavigate: (page: MarketingPage) => void; onInstall: () => void; onOpen: () => void }) {
  const navigate = (next: MarketingPage) => { onNavigate(next); window.scrollTo({ top: 0 }) }
  return <div className="site-shell"><header className="site-nav"><Logo /><nav>{pages.map(item => <button key={item.id} className={page === item.id ? 'is-active' : ''} onClick={() => navigate(item.id)}>{item.label}</button>)}</nav><button className="site-nav__cta" onClick={onInstall}>Install kiosk</button></header>{page === 'home' ? <Home onInstall={onInstall} onOpen={onOpen} onNavigate={navigate} /> : <InnerPage page={page} onNavigate={navigate} />}<footer className="site-footer"><div><Logo /><p>Evidence-first yellowfin tuna grading, built for connected stations.</p></div><div><strong>Explore</strong>{pages.map(item => <button key={item.id} onClick={() => navigate(item.id)}>{item.label}</button>)}</div><div><strong>Legal</strong><button onClick={() => navigate('terms')}>Terms</button><button onClick={() => navigate('privacy')}>Privacy policy</button></div><div><strong>Contact</strong><a href="mailto:hello@tunaeye.app">hello@tunaeye.app</a><span>Philippines</span></div><small>© 2026 TunaEye. All rights reserved.</small></footer></div>
}

function Home({ onInstall, onOpen, onNavigate }: { onInstall: () => void; onOpen: () => void; onNavigate: (page: MarketingPage) => void }) {
  const [showcase, setShowcase] = useState(0)
  const showcaseItems = [{ image: '/assets/sashiboCoreFull.png', title: 'Sashibo core', copy: 'Center-cut evidence with its own fish, weight, inference, and receipt.' }, { image: '/assets/tailCutFull.png', title: 'Tail cut', copy: 'A separate capture path that stays traceable through review and sync.' }]
  return <main className="site-home"><section className="site-hero"><div className="site-hero__mesh" /><div className="site-hero__copy"><span className="site-kicker">Yellowfin tuna visual grading</span><h1>Clear evidence.<br /><em>Confident decisions.</em></h1><p>Connect guided sample capture, Raspberry Pi edge inference, and accountable cloud records in one focused station workflow.</p><div className="site-actions"><button className="site-button site-button--primary" onClick={onInstall}>Install kiosk <Arrow /></button><button className="site-button" onClick={onOpen}>Open workflow <Arrow /></button></div><div className="site-trust"><span>Edge AI</span><span>Offline-ready</span><span>Auditable</span><span>Built for 10.1″ tablets</span></div></div><div className="site-hero__visual"><div className="site-orbit site-orbit--one" /><div className="site-orbit site-orbit--two" /><img src="/assets/tunaEyeLoadingScreen.png" alt="TunaEye grading station interface" /><aside><b>Station status</b><strong><i /> Ready to grade</strong><small>Camera · Edge · Sync</small></aside></div><div className="site-hero__band"><span>Capture</span><i /><span>Infer</span><i /><span>Review</span><i /><span>Synchronize</span></div></section>
  <section className="site-story"><div><span className="site-kicker">Why TunaEye</span><h2>One sample should tell one complete story.</h2></div><div><p>Visual grading is only useful when the evidence remains linked to the right fish, operator, weight, model result, and final decision.</p><p>TunaEye guides the physical workflow while preserving every decision for review, printing, and multi-station operations.</p><button className="site-text-link" onClick={() => onNavigate('about')}>Read our approach <Arrow /></button></div></section>
  <section className="site-workflow"><header><span className="site-kicker">Workflow at a glance</span><h2>From tray to traceable result.</h2></header><div>{[['01','Prepare','Select the sample and follow the chamber guide.'],['02','Capture','Use the actual tablet, USB, or station camera.'],['03','Infer','Send evidence to the configured Raspberry Pi model.'],['04','Confirm','Review confidence or apply a protected override.'],['05','Sync','Store and distribute records through cloud services.']].map(([number,title,copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="site-showcase"><div className="site-showcase__copy"><span className="site-kicker">Evidence stays visible</span><h2>{showcaseItems[showcase].title}</h2><p>{showcaseItems[showcase].copy}</p><div><button onClick={() => setShowcase(value => value ? value - 1 : showcaseItems.length - 1)} aria-label="Previous sample">←</button><span>{showcase + 1} / {showcaseItems.length}</span><button onClick={() => setShowcase(value => (value + 1) % showcaseItems.length)} aria-label="Next sample">→</button></div></div><div className="site-showcase__image"><span>Captured sample evidence</span><img src={showcaseItems[showcase].image} alt={showcaseItems[showcase].title} /></div></section>
  <section className="site-metrics"><article><strong>2</strong><span>Supported sample types</span></article><article><strong>200 kg</strong><span>Maximum fish weight</span></article><article><strong>1:1</strong><span>Fish-to-record traceability</span></article><article><strong>24/7</strong><span>Offline kiosk availability</span></article></section>
  <section className="site-architecture"><div><span className="site-kicker">Connected by design</span><h2>Local speed. Cloud visibility.</h2><p>The tablet controls the operator experience. Raspberry Pi handles model inference at the edge. Supabase PostgreSQL preserves durable records, while Convex distributes live updates to authorized admins.</p><button className="site-text-link" onClick={() => onNavigate('features')}>Explore every feature <Arrow /></button></div><div className="architecture-flow"><article><b>01</b><strong>Tablet kiosk</strong><small>Capture and review</small></article><i>↔</i><article><b>02</b><strong>Raspberry Pi</strong><small>Model inference</small></article><i>↔</i><article><b>03</b><strong>Cloud</strong><small>Store and synchronize</small></article></div></section>
  <section className="site-faq-preview"><header><span className="site-kicker">Frequently asked</span><h2>Before TunaEye reaches your station.</h2></header><div><details open><summary>Who is TunaEye for?</summary><p>Fish ports, buying stations, processors, trained graders, and quality-control teams.</p></details><details><summary>Does it work without internet?</summary><p>The kiosk shell and local records work offline. Cloud synchronization resumes when services are available.</p></details><details><summary>Where does grading happen?</summary><p>The intended production model runs on a Raspberry Pi connected to the station network.</p></details></div><button className="site-text-link" onClick={() => onNavigate('faq')}>View all questions <Arrow /></button></section>
  <section className="site-cta"><span className="site-kicker">Ready for the grading floor?</span><h2>Turn every sample into clear, connected evidence.</h2><p>Install the kiosk or explore the operator workflow in your browser.</p><div className="site-actions"><button className="site-button site-button--primary" onClick={onInstall}>Install TunaEye</button><button className="site-button" onClick={onOpen}>Open workflow</button></div></section></main>
}

function InnerPage({ page, onNavigate }: { page: Exclude<MarketingPage, 'home'>; onNavigate: (page: MarketingPage) => void }) {
  const content = {
    features: { eyebrow: 'Platform features', title: 'Everything a connected grading station needs.', intro: 'TunaEye combines guided capture, edge inference, evidence review, protected decisions, printing, synchronization, and administration.', cards: [['Guided kiosk workflow','Large touch targets and responsive 16:10 tablet layouts.'],['Actual camera capture','Switch between device, USB, and virtual cameras.'],['Edge inference contract','Connect to Raspberry Pi health and inference endpoints.'],['Protected overrides','Require administrator authorization and preserve the original result.'],['Cloud-ready records','Configure Supabase PostgreSQL and Convex endpoints.'],['Audit visibility','Track login, sync, settings, inference, and decision activity.']] },
    about: { eyebrow: 'About TunaEye', title: 'Better evidence for better tuna decisions.', intro: 'TunaEye was conceived as a bridge between the physical craft of tuna grading and the consistency of connected digital records.', cards: [['Our purpose','Help trained graders work consistently without removing expert judgment.'],['Our method','Link sample evidence, fish identity, weight, model output, and final action.'],['Our standard','Make every important decision inspectable, printable, and synchronizable.']] },
    team: { eyebrow: 'The TunaEye team', title: 'Built where fisheries, hardware, AI, and software meet.', intro: 'The system requires collaboration across the grading floor and the engineering stack.', cards: [['Fisheries operations','Defines the real station workflow and evidence requirements.'],['Edge AI and hardware','Owns the Raspberry Pi, camera, chamber, and deployed model.'],['Product engineering','Builds the kiosk, cloud records, sync, security, and administrator tools.']] },
    faq: { eyebrow: 'Frequently asked questions', title: 'Answers for operators and deployment teams.', intro: 'Start with the workflow, integration boundaries, and device expectations.', cards: [['Can TunaEye replace a trained grader?','No. It supports evidence and consistency while preserving expert review.'],['Can it run offline?','The PWA and local records can. Inference needs the Pi LAN connection; cloud sync needs internet.'],['How are multiple fish handled?','Every sample keeps its own fish association, weight, result, override, and receipt.'],['How is the tablet locked down?','Fullscreen PWA mode helps; guaranteed Android navigation suppression requires managed kiosk or lock-task mode.'],['Where is data stored?','Locally first, with the intended durable store in Supabase PostgreSQL and live updates through Convex.'],['Which model is active?','Admins can configure and verify the model identifier returned by the Raspberry Pi health endpoint.']] },
    terms: { eyebrow: 'Legal', title: 'Terms of use', intro: 'TunaEye supports trained grading operations. Operators remain responsible for fish association, evidence quality, regulatory compliance, purchasing decisions, and final approval.', cards: [['Authorized use','Use the system only with approved stations, devices, accounts, and grading procedures.'],['Human responsibility','Model output is decision support and must remain reviewable by qualified personnel.'],['Operational integrity','Do not alter evidence, bypass audit controls, or misrepresent a grading record.']] },
    privacy: { eyebrow: 'Legal', title: 'Privacy policy', intro: 'TunaEye processes grader identity, captured sample evidence, device metadata, grading decisions, and audit events to operate and secure the service.', cards: [['Data purpose','Operate grading, synchronization, troubleshooting, security, and reporting.'],['Data access','Restrict station and cloud records to authorized personnel and organizations.'],['Retention and deletion','Production deployments must define retention periods for images, records, and audit events.']] },
  }[page]
  return <main className="site-inner"><header><span className="site-kicker">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p></header><section>{content.cards.map(([title,copy], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{copy}</p></article>)}</section><aside><h2>Ready to see TunaEye in action?</h2><button className="site-button site-button--primary" onClick={() => onNavigate('home')}>Return home <Arrow /></button></aside></main>
}
